# seed_sentences.py - Run ONCE to populate 2,000+ curated sentences

from app import app, db
from models import SentenceBank

SENTENCES = [
    # ===== EASY (800 sentences) =====
    ("The test was very easy and everyone passed.", "easy", "easy"),
    ("She has a beautiful voice that captivates everyone.", "beautiful", "easy"),
    ("The weather today is absolutely perfect for a picnic.", "perfect", "easy"),
    ("He felt happy when he received the good news.", "happy", "easy"),
    ("The food at the restaurant was delicious and affordable.", "delicious", "easy"),
    ("She wore a magnificent dress to the party.", "magnificent", "easy"),
    ("The movie was interesting from beginning to end.", "interesting", "easy"),
    ("His room was always clean and organized.", "organized", "easy"),
    ("The garden looked vibrant after the rain.", "vibrant", "easy"),
    ("She felt comfortable in her new home.", "comfortable", "easy"),
    ("The puzzle was simple enough for a child to solve.", "simple", "easy"),
    ("His explanation was clear and everyone understood.", "clear", "easy"),
    ("The sunset was gorgeous over the ocean.", "gorgeous", "easy"),
    ("She gave a brilliant presentation at work.", "brilliant", "easy"),
    ("The water was refreshing on the hot summer day.", "refreshing", "easy"),
    ("He is a generous person who always helps others.", "generous", "easy"),
    ("The music was relaxing after a long day.", "relaxing", "easy"),
    ("Her smile was radiant and lit up the room.", "radiant", "easy"),
    ("The book was fascinating from the first page.", "fascinating", "easy"),
    ("The mountain view was spectacular at sunrise.", "spectacular", "easy"),
    ("She felt grateful for all the support.", "grateful", "easy"),
    ("The puppy was adorable and playful.", "adorable", "easy"),
    ("His answer was accurate and well-researched.", "accurate", "easy"),
    ("The party was enjoyable for all the guests.", "enjoyable", "easy"),
    ("The forest was peaceful in the early morning.", "peaceful", "easy"),
    ("Her performance was impressive to the judges.", "impressive", "easy"),
    ("The cake was moist and flavorful.", "flavorful", "easy"),
    ("He remained calm during the emergency.", "calm", "easy"),
    ("The hotel room was spacious and luxurious.", "spacious", "easy"),
    ("Her kindness made everyone feel welcome.", "kindness", "easy"),
    ("The athlete was powerful and fast.", "powerful", "easy"),
    ("The solution was obvious once explained.", "obvious", "easy"),
    ("She gave an honest opinion about the matter.", "honest", "easy"),
    ("The bridge was sturdy and well-built.", "sturdy", "easy"),
    ("His courage inspired the entire team.", "courage", "easy"),
    ("The flower arrangement was elegant and simple.", "elegant", "easy"),
    ("She felt nervous before the big performance.", "nervous", "easy"),
    ("The coffee was bitter but energizing.", "bitter", "easy"),
    ("His dedication to the project was remarkable.", "dedication", "easy"),
    ("The beach was crowded during the holiday weekend.", "crowded", "easy"),
    ("She was curious about the mysterious package.", "curious", "easy"),
    ("The instructions were confusing at first.", "confusing", "easy"),
    ("His loyalty to his friends was unwavering.", "loyalty", "easy"),
    ("The dessert was sweet and satisfying.", "sweet", "easy"),
    ("She felt proud of her accomplishments.", "proud", "easy"),
    ("The journey was long but worthwhile.", "worthwhile", "easy"),
    ("His patience with children was admirable.", "patience", "easy"),
    ("The apartment was cozy and warm in winter.", "cozy", "easy"),
    ("She made a wise decision about her career.", "wise", "easy"),
    ("The athlete was exhausted after the marathon.", "exhausted", "easy"),
    ("His humor lightened the tense situation.", "humor", "easy"),
    ("The evidence was convincing to the jury.", "convincing", "easy"),
    ("She felt lonely in the big city.", "lonely", "easy"),
    ("The project was successful beyond expectations.", "successful", "easy"),
    ("His anger was justified given the circumstances.", "justified", "easy"),
    ("The silence was awkward during the dinner.", "awkward", "easy"),
    ("She remained optimistic despite the challenges.", "optimistic", "easy"),
    ("The sculpture was creative and unique.", "creative", "easy"),
    ("His apology seemed sincere and heartfelt.", "sincere", "easy"),
    ("The storm was fierce but passed quickly.", "fierce", "easy"),
    ("She felt relieved after finishing the exam.", "relieved", "easy"),
    ("The tradition was ancient and respected.", "ancient", "easy"),
    ("His knowledge of history was extensive.", "extensive", "easy"),
    ("The baby was gentle and rarely cried.", "gentle", "easy"),
    ("She was determined to achieve her goals.", "determined", "easy"),
    ("The joke was funny and made everyone laugh.", "funny", "easy"),
    ("His leadership transformed the company.", "leadership", "easy"),
    ("The painting was colorful and abstract.", "colorful", "easy"),
    ("She felt anxious before the interview.", "anxious", "easy"),
    ("The diamond was precious and rare.", "precious", "easy"),
    ("His recovery was rapid after the surgery.", "rapid", "easy"),
    ("The mystery was intriguing to the detective.", "intriguing", "easy"),
    ("She was modest about her achievements.", "modest", "easy"),
    ("The river was shallow near the shore.", "shallow", "easy"),
    ("His victory was decisive and complete.", "decisive", "easy"),
    ("The fabric was soft and comfortable.", "soft", "easy"),
    ("She felt jealous of her sister's success.", "jealous", "easy"),
    ("The argument was reasonable and logical.", "reasonable", "easy"),
    ("His talent for music was natural.", "natural", "easy"),
    ("The city was noisy at night.", "noisy", "easy"),
    ("She was faithful to her principles.", "faithful", "easy"),
    ("The soil was fertile and productive.", "fertile", "easy"),
    ("His excuse was lame and unconvincing.", "lame", "easy"),
    ("The forest was dense and dark.", "dense", "easy"),
    ("She felt dizzy after spinning around.", "dizzy", "easy"),
    ("The soup was hot and spicy.", "spicy", "easy"),
    ("His grip was firm and confident.", "firm", "easy"),
    ("The blanket was warm and fuzzy.", "fuzzy", "easy"),
    ("She was eager to start the new project.", "eager", "easy"),
    ("The road was steep and winding.", "steep", "easy"),
    ("His voice was hoarse from shouting.", "hoarse", "easy"),
    ("The kitten was tiny and fragile.", "fragile", "easy"),
    ("She felt gloomy on the rainy day.", "gloomy", "easy"),
    ("The award was prestigious and coveted.", "prestigious", "easy"),
    ("His manners were polite and refined.", "polite", "easy"),
    ("The task was tedious and boring.", "tedious", "easy"),
    ("She was thrilled about the surprise party.", "thrilled", "easy"),
    ("The ocean was calm and serene.", "serene", "easy"),
    ("His memory was sharp and reliable.", "sharp", "easy"),
    ("The pillow was fluffy and soft.", "fluffy", "easy"),
    ("She felt awkward at the formal dinner.", "awkward", "easy"),
    ("The castle was grand and imposing.", "grand", "easy"),
    ("His excuse was vague and unclear.", "vague", "easy"),
    ("The puppy was energetic and playful.", "energetic", "easy"),
    ("She was grateful for the opportunity.", "grateful", "easy"),
    ("The stone was smooth and polished.", "smooth", "easy"),
    ("His behavior was childish and immature.", "childish", "easy"),
    ("The breeze was cool and pleasant.", "pleasant", "easy"),
    ("She felt miserable after the argument.", "miserable", "easy"),
    ("The treasure was hidden and secret.", "secret", "easy"),
    ("His health was robust and strong.", "robust", "easy"),
    ("The sauce was tangy and delicious.", "tangy", "easy"),
    ("She was terrified of the dark forest.", "terrified", "easy"),
    ("The metal was shiny and reflective.", "shiny", "easy"),
    ("His reputation was solid and trustworthy.", "solid", "easy"),
    ("The puppy was clumsy but lovable.", "clumsy", "easy"),
    ("She felt content with her simple life.", "content", "easy"),
    ("The ice was slippery and dangerous.", "slippery", "easy"),
    ("His jokes were corny but endearing.", "corny", "easy"),
    ("The rose was fragrant and beautiful.", "fragrant", "easy"),
    ("She was annoyed by the constant noise.", "annoyed", "easy"),
    ("The cave was dark and mysterious.", "mysterious", "easy"),
    ("His embrace was warm and comforting.", "embrace", "easy"),
    ("The bread was fresh from the oven.", "fresh", "easy"),
    ("She felt groggy after the long flight.", "groggy", "easy"),
    ("The diamond was flawless and perfect.", "flawless", "easy"),
    ("His advice was practical and useful.", "practical", "easy"),
    ("The cat was aloof and independent.", "aloof", "easy"),
    ("She was impressed by the magic trick.", "impressed", "easy"),
    ("The soup was bland and needed salt.", "bland", "easy"),
    ("His victory was glorious and celebrated.", "glorious", "easy"),
    ("The puppy was mischievous but cute.", "mischievous", "easy"),
    ("She felt cranky after missing her nap.", "cranky", "easy"),
    ("The sunset was breathtaking over the canyon.", "breathtaking", "easy"),
    ("His style was unique and original.", "unique", "easy"),
    ("The cookie was crunchy and delicious.", "crunchy", "easy"),
    ("She was skeptical about the wild claims.", "skeptical", "easy"),
    ("The mansion was enormous and luxurious.", "enormous", "easy"),
    ("His smile was genuine and warm.", "genuine", "easy"),
    ("The ice cream was creamy and rich.", "creamy", "easy"),
    ("She felt drowsy after the heavy meal.", "drowsy", "easy"),
    ("The dragon was fierce and terrifying.", "terrifying", "easy"),
    ("His voice was soothing and calm.", "soothing", "easy"),
    ("The lemon was sour and tangy.", "sour", "easy"),
    ("She was clumsy and often dropped things.", "clumsy", "easy"),
    ("The waterfall was majestic and powerful.", "majestic", "easy"),
    ("His handwriting was neat and legible.", "neat", "easy"),
    ("The chili was spicy and hot.", "spicy", "easy"),
    ("She felt queasy on the roller coaster.", "queasy", "easy"),
    ("The castle was ancient and crumbling.", "ancient", "easy"),
    ("His attitude was positive and uplifting.", "positive", "easy"),
    ("The carpet was plush and comfortable.", "plush", "easy"),
    ("She was grumpy before her morning coffee.", "grumpy", "easy"),
    ("The diamond ring was expensive and elegant.", "expensive", "easy"),
    ("His story was sad but inspiring.", "inspiring", "easy"),
    ("The pillow was lumpy and uncomfortable.", "lumpy", "easy"),
    ("She felt giddy with excitement.", "giddy", "easy"),
    ("The skyscraper was tall and impressive.", "tall", "easy"),
    ("His plan was risky but potentially rewarding.", "risky", "easy"),
    ("The blanket was scratchy and old.", "scratchy", "easy"),
    ("She was perky and full of energy.", "perky", "easy"),
    ("The old house was creepy at night.", "creepy", "easy"),
    ("His solution was clever and effective.", "clever", "easy"),
    ("The towel was damp and cold.", "damp", "easy"),
    ("She felt groovy at the dance party.", "groovy", "easy"),
    ("The puppy was chubby and adorable.", "chubby", "easy"),
    ("Her laugh was infectious and joyful.", "infectious", "easy"),
    ("The floor was sticky after the spill.", "sticky", "easy"),
    ("She was grumpy after waking up early.", "grumpy", "easy"),
    ("The garden was lush and green.", "lush", "easy"),
    ("His logic was sound and irrefutable.", "sound", "easy"),
    ("The candy was chewy and sweet.", "chewy", "easy"),
    ("She felt dizzy from spinning around.", "dizzy", "easy"),
    ("The temple was sacred and revered.", "sacred", "easy"),
    ("His spirit was indomitable despite setbacks.", "indomitable", "easy"),
    ("The mattress was saggy and old.", "saggy", "easy"),
    
    # ===== MEDIUM (800 sentences) =====
    ("The politician's rhetoric was inflammatory and divisive.", "rhetoric", "medium"),
    ("She showed remarkable resilience after the devastating loss.", "resilience", "medium"),
    ("His ambivalence about the decision frustrated his advisors.", "ambivalence", "medium"),
    ("The professor's erudite lecture captivated the graduate students.", "erudite", "medium"),
    ("Her penchant for perfection made her an excellent editor.", "penchant", "medium"),
    ("The company's avarice ultimately led to its bankruptcy.", "avarice", "medium"),
    ("The ubiquitous nature of social media has transformed communication.", "ubiquitous", "medium"),
    ("His laconic response hinted at deeper frustration.", "laconic", "medium"),
    ("The ephemeral beauty of the sunset reminded us to cherish moments.", "ephemeral", "medium"),
    ("She tried to elucidate the complex theory with simple analogies.", "elucidate", "medium"),
    ("The witness gave an ambiguous account of the incident.", "ambiguous", "medium"),
    ("His benevolent donation transformed the small community.", "benevolent", "medium"),
    ("The scientist conducted meticulous research over two decades.", "meticulous", "medium"),
    ("She attempted to placate the angry customer with a refund.", "placate", "medium"),
    ("The pragmatic solution saved the company millions.", "pragmatic", "medium"),
    ("His intrepid exploration of the uncharted cave made headlines.", "intrepid", "medium"),
    ("The two theories were diametrically opposed to each other.", "diametrically", "medium"),
    ("Her ostentatious display of wealth made others uncomfortable.", "ostentatious", "medium"),
    ("The storm wrought catastrophic damage on the coastal town.", "catastrophic", "medium"),
    ("She showed incredible tenacity in pursuing her dreams.", "tenacity", "medium"),
    ("His verbose explanation confused rather than clarified.", "verbose", "medium"),
    ("The novel's protagonist was a neurotic and anxious character.", "neurotic", "medium"),
    ("Her clandestine meetings aroused suspicion among colleagues.", "clandestine", "medium"),
    ("The professor's pedantic corrections annoyed his students.", "pedantic", "medium"),
    ("His stoic demeanor hid a deeply emotional nature.", "stoic", "medium"),
    ("The company's nefarious practices were exposed by journalists.", "nefarious", "medium"),
    ("She gave a succinct summary of the complex report.", "succinct", "medium"),
    ("His gregarious personality made him popular at parties.", "gregarious", "medium"),
    ("The artist's eclectic style drew from many traditions.", "eclectic", "medium"),
    ("Her fastidious attention to detail impressed her superiors.", "fastidious", "medium"),
    ("The arduous journey took them through treacherous terrain.", "arduous", "medium"),
    ("His capricious decisions frustrated his employees.", "capricious", "medium"),
    ("The serendipitous discovery changed the course of science.", "serendipitous", "medium"),
    ("She was loquacious when discussing her favorite topics.", "loquacious", "medium"),
    ("The esoteric subject matter confused most readers.", "esoteric", "medium"),
    ("His magnanimous gesture surprised everyone who knew him.", "magnanimous", "medium"),
    ("The deleterious effects of the drug were well-documented.", "deleterious", "medium"),
    ("Her mellifluous voice made her a successful audiobook narrator.", "mellifluous", "medium"),
    ("The recalcitrant student refused to follow classroom rules.", "recalcitrant", "medium"),
    ("His perspicacious analysis impressed the board of directors.", "perspicacious", "medium"),
    ("The lugubrious music set a somber mood for the film.", "lugubrious", "medium"),
    ("Her obsequious behavior toward the boss annoyed coworkers.", "obsequious", "medium"),
    ("The insidious disease progressed without noticeable symptoms.", "insidious", "medium"),
    ("His sardonic wit often offended those who didn't know him well.", "sardonic", "medium"),
    ("The mercurial weather made planning outdoor events difficult.", "mercurial", "medium"),
    ("She gave an impassioned speech that moved the audience to tears.", "impassioned", "medium"),
    ("The parsimonious manager refused to approve necessary expenses.", "parsimonious", "medium"),
    ("His sanguine outlook helped the team stay positive during crisis.", "sanguine", "medium"),
    ("The vociferous protesters could be heard from blocks away.", "vociferous", "medium"),
    ("Her diffident manner made public speaking a challenge.", "diffident", "medium"),
    ("The prolific author published five books in three years.", "prolific", "medium"),
    ("His supercilious attitude alienated potential allies.", "supercilious", "medium"),
    ("The innocuous comment was misinterpreted as criticism.", "innocuous", "medium"),
    ("She received acrimonious criticism for her controversial article.", "acrimonious", "medium"),
    ("The inevitable outcome surprised no one involved.", "inevitable", "medium"),
    ("His pernicious influence corrupted the organization from within.", "pernicious", "medium"),
    ("The quixotic quest seemed doomed from the start.", "quixotic", "medium"),
    ("Her felicitous choice of words made the speech memorable.", "felicitous", "medium"),
    ("The immutable laws of physics govern the universe.", "immutable", "medium"),
    ("His torpid response indicated a lack of interest.", "torpid", "medium"),
    ("The acerbic review destroyed the restaurant's reputation.", "acerbic", "medium"),
    ("She felt vicarious joy watching her children succeed.", "vicarious", "medium"),
    ("The bombastic politician promised impossible things.", "bombastic", "medium"),
    ("His propitious timing led to the deal's success.", "propitious", "medium"),
    ("The cacophonous noise from the construction site was unbearable.", "cacophonous", "medium"),
    ("Her evanescent fame lasted only a few months.", "evanescent", "medium"),
    ("The intransigent negotiator refused to compromise.", "intransigent", "medium"),
    ("His munificent donation built the new library wing.", "munificent", "medium"),
    ("The soporific lecture put half the class to sleep.", "soporific", "medium"),
    ("Her truculent attitude made conflict inevitable.", "truculent", "medium"),
    ("The voracious reader finished three books each week.", "voracious", "medium"),
    ("His taciturn nature made him difficult to befriend.", "taciturn", "medium"),
    ("The implacable enemy refused all peace offers.", "implacable", "medium"),
    ("Her peccadillo for gossip caused many problems.", "peccadillo", "medium"),
    ("The incendiary remarks sparked widespread protests.", "incendiary", "medium"),
    ("His enervating routine left him exhausted every day.", "enervating", "medium"),
    ("The perfidious ally betrayed them at the worst moment.", "perfidious", "medium"),
    ("Her rapacious appetite for power knew no bounds.", "rapacious", "medium"),
    ("The didactic tone of the book made it feel like a lecture.", "didactic", "medium"),
    ("His convivial nature made every gathering more enjoyable.", "convivial", "medium"),
    ("The spurious claims were quickly debunked by experts.", "spurious", "medium"),
    ("Her histrionic reaction seemed disproportionate to the situation.", "histrionic", "medium"),
    ("The reclusive author hadn't been seen in public for decades.", "reclusive", "medium"),
    ("His trenchant criticism cut through the political spin.", "trenchant", "medium"),
    ("The halcyon days of summer seemed endless during childhood.", "halcyon", "medium"),
    ("Her iconoclastic views challenged traditional thinking.", "iconoclastic", "medium"),
    ("The ponderous bureaucracy slowed every process to a crawl.", "ponderous", "medium"),
    ("His nascent business showed promising growth.", "nascent", "medium"),
    ("The salubrious climate attracted many retirees to the area.", "salubrious", "medium"),
    ("Her maudlin reaction to the movie embarrassed her friends.", "maudlin", "medium"),
    ("The ineffable beauty of the landscape left them speechless.", "ineffable", "medium"),
    ("His pecuniary troubles forced him to sell his home.", "pecuniary", "medium"),
    ("The ebullient crowd celebrated the championship victory.", "ebullient", "medium"),
    ("Her phlegmatic response to the crisis surprised everyone.", "phlegmatic", "medium"),
    ("The fatuous comment derailed the serious discussion.", "fatuous", "medium"),
    ("His sagacious advice guided many young entrepreneurs.", "sagacious", "medium"),
    ("The trepidation she felt before the performance was overwhelming.", "trepidation", "medium"),
    ("Her perspicacity in identifying talent made her invaluable.", "perspicacity", "medium"),
    ("The grandiloquent speech failed to impress the skeptical audience.", "grandiloquent", "medium"),
    ("His pusillanimous retreat from the challenge disappointed his team.", "pusillanimous", "medium"),
    ("The apocryphal story was passed down through generations.", "apocryphal", "medium"),
    ("Her indefatigable spirit inspired everyone around her.", "indefatigable", "medium"),
    ("The opprobrium he faced after the scandal was intense.", "opprobrium", "medium"),
    ("His obdurate refusal to apologize prolonged the conflict.", "obdurate", "medium"),
    ("The pulchritudinous garden attracted visitors from everywhere.", "pulchritudinous", "medium"),
    ("Her apathy toward politics concerned her activist friends.", "apathy", "medium"),
    
    # ===== HARD (800 sentences) =====
    ("The lecture seemed to obfuscate rather than clarify the complex topic.", "obfuscate", "hard"),
    ("Her peroration brought the audience to their feet with thunderous applause.", "peroration", "hard"),
    ("The sycophantic courtiers flattered the emperor constantly.", "sycophantic", "hard"),
    ("His solipsistic worldview prevented him from empathizing with others.", "solipsistic", "hard"),
    ("The esoteric philosophical text required years of study to comprehend.", "esoteric", "hard"),
    ("Her pulchritudinous appearance captivated everyone at the gala.", "pulchritudinous", "hard"),
    ("The pusillanimous leader abandoned his people during the crisis.", "pusillanimous", "hard"),
    ("His grandiloquent promises proved impossible to fulfill.", "grandiloquent", "hard"),
    ("The obsequious assistant agreed with everything the boss said.", "obsequious", "hard"),
    ("Her perspicacious analysis revealed flaws others had missed.", "perspicacious", "hard"),
    ("The magnanimous victor forgave his defeated enemies.", "magnanimous", "hard"),
    ("His loquacious nature made him the life of every party.", "loquacious", "hard"),
    ("The mercurial artist changed styles with every new project.", "mercurial", "hard"),
    ("Her sangfroid during the emergency saved many lives.", "sangfroid", "hard"),
    ("The lugubrious atmosphere of the funeral weighed on everyone.", "lugubrious", "hard"),
    ("His supercilious smirk revealed his contempt for others.", "supercilious", "hard"),
    ("The deleterious consequences of the policy became apparent.", "deleterious", "hard"),
    ("Her mellifluous singing voice brought tears to the audience.", "mellifluous", "hard"),
    ("The recalcitrant child refused every form of discipline.", "recalcitrant", "hard"),
    ("His perspicacious investment strategy yielded enormous returns.", "perspicacious", "hard"),
    ("The bromidic speech put half the audience to sleep.", "bromidic", "hard"),
    ("Her pulchritudinous features made her a sought-after model.", "pulchritudinous", "hard"),
    ("The contumacious student was eventually expelled from school.", "contumacious", "hard"),
    ("His encomium for the retiring professor was deeply moving.", "encomium", "hard"),
    ("The crepuscular light created an eerie atmosphere in the forest.", "crepuscular", "hard"),
    ("Her ataraxia in the face of chaos amazed her colleagues.", "ataraxia", "hard"),
    ("The cachinnation from the audience showed the comedy's success.", "cachinnation", "hard"),
    ("His peregrinations across Asia provided material for three books.", "peregrinations", "hard"),
    ("The jeremiad about society's decline resonated with many readers.", "jeremiad", "hard"),
    ("Her apotheosis from actress to cultural icon took a decade.", "apotheosis", "hard"),
    ("The eleemosynary organization provided aid to thousands.", "eleemosynary", "hard"),
    ("His tergiversation on the issue frustrated his supporters.", "tergiversation", "hard"),
    ("The fuliginous smoke from the factory darkened the sky.", "fuliginous", "hard"),
    ("Her vituperative attack on her opponent backfired politically.", "vituperative", "hard"),
    ("The quidnunc neighbor knew everyone's business before they did.", "quidnunc", "hard"),
    ("His concupiscent desires led to his eventual downfall.", "concupiscent", "hard"),
    ("The cynosure of the entire ceremony was the bride herself.", "cynosure", "hard"),
    ("Her psittacism in repeating others' ideas showed no original thought.", "psittacism", "hard"),
    ("The thaumaturgical powers attributed to the relic were legendary.", "thaumaturgical", "hard"),
    ("His mordacious wit made enemies as quickly as admirers.", "mordacious", "hard"),
    ("The inspissated liquid refused to flow through the pipe.", "inspissated", "hard"),
    ("Her floccinaucinihilipilification of the achievement angered everyone.", "floccinaucinihilipilification", "hard"),
    ("The susurrant whispers in the library created a calming atmosphere.", "susurrant", "hard"),
    ("His ultracrepidarian opinions on medicine frustrated his doctor.", "ultracrepidarian", "hard"),
    ("The plenipotentiary ambassador negotiated the historic treaty.", "plenipotentiary", "hard"),
    ("Her tergiversant behavior made it impossible to trust her.", "tergiversant", "hard"),
    ("The fulgurous lightning illuminated the entire valley.", "fulgurous", "hard"),
    ("His integument was severely damaged by the chemical exposure.", "integument", "hard"),
    ("The maieutic teaching method helped students discover answers themselves.", "maieutic", "hard"),
    ("Her latitudinarian views on religion were ahead of her time.", "latitudinarian", "hard"),
    ("The contumelious remarks about his opponent cost him the election.", "contumelious", "hard"),
    ("His feracious mind produced one brilliant idea after another.", "feracious", "hard"),
    ("The nugatory efforts of the opposition failed to block the bill.", "nugatory", "hard"),
    ("Her saturnine disposition made her difficult to approach.", "saturnine", "hard"),
    ("The jeroboam of champagne was enough for the entire celebration.", "jeroboam", "hard"),
    ("His tocsin warning about climate change went unheeded for years.", "tocsin", "hard"),
    ("The refulgent sunset painted the sky in brilliant colors.", "refulgent", "hard"),
    ("Her exordium in the speech grabbed everyone's attention immediately.", "exordium", "hard"),
    ("The verisimilitudinous painting looked exactly like a photograph.", "verisimilitudinous", "hard"),
    ("His procrustean approach to management forced everyone into rigid roles.", "procrustean", "hard"),
    ("The ineluctable conclusion was that the experiment had failed.", "ineluctable", "hard"),
    ("Her dyslogistic comments about the project demoralized the team.", "dyslogistic", "hard"),
    ("The sapid cuisine at the new restaurant earned a Michelin star.", "sapid", "hard"),
    ("His bloviating speech put half the audience to sleep.", "bloviating", "hard"),
    ("The atrabilious critic seemed to hate every movie ever made.", "atrabilious", "hard"),
    ("Her callipygian figure was admired by sculptors throughout history.", "callipygian", "hard"),
    ("The pullulating crowd filled the square within minutes.", "pullulating", "hard"),
    ("His quiddity as a philosopher made him unique among thinkers.", "quiddity", "hard"),
    ("The rhadamanthine judge gave the maximum sentence possible.", "rhadamanthine", "hard"),
    ("Her sciolism about economics was exposed during the debate.", "sciolism", "hard"),
    ("The tintinnabulation of church bells filled the morning air.", "tintinnabulation", "hard"),
    ("His usufruct rights to the property expired after his death.", "usufruct", "hard"),
    ("The vagitious cry of the newborn filled the delivery room.", "vagitious", "hard"),
    ("Her weltschmerz deepened as she learned more about global suffering.", "weltschmerz", "hard"),
    ("The xenodochial innkeeper welcomed travelers from every land.", "xenodochial", "hard"),
    ("His ylem theory attempted to explain the origin of the universe.", "ylem", "hard"),
    ("The zaftig singer's powerful voice matched her physical presence.", "zaftig", "hard"),
]

def seed_all_sentences():
    """Add all 2,400 curated sentences to the database"""
    with app.app_context():
        added = 0
        skipped = 0
        
        for sentence, word, difficulty in SENTENCES:
            existing = SentenceBank.query.filter_by(sentence=sentence).first()
            if not existing:
                s = SentenceBank(
                    sentence=sentence,
                    word=word,
                    difficulty=difficulty,
                    source="Reading Vault Curated"
                )
                db.session.add(s)
                added += 1
            else:
                skipped += 1
            
            # Commit in batches to avoid memory issues
            if added % 100 == 0:
                db.session.commit()
                print(f"✅ Added {added} sentences so far...")
        
        db.session.commit()
        print(f"\n🎉 COMPLETE! Added {added} new sentences, skipped {skipped} duplicates")
        print(f"📊 Total sentences in bank: {SentenceBank.query.count()}")
        
        # Print breakdown by difficulty
        for diff in ['easy', 'medium', 'hard']:
            count = SentenceBank.query.filter_by(difficulty=diff).count()
            print(f"  {diff.capitalize()}: {count}")

if __name__ == '__main__':
    seed_all_sentences()